global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fastapi_ml'
    static_configs:
      - targets: ['host.docker.internal:8000']   

rule_files:
  - "alert_rules.yml" 

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']
